# Generated by Django 5.0.1 on 2024-01-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comment_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-date_posted',)},
        ),
    ]
